#!/bin/bash
# George Chacko 10/21/2017

echo "This script takes a set of source files and modifies them to incorporate xml tags then
it assembles a complete xml file that is compliant with seedset.dtd

Input filenames should terminate in '_pmid' and should include

2 fda_*_pmid    files
1 npl_pmid      file
4 ct_*_pmid     files
5 pubmed_*_pmid files
"
# sleep 1

ls AnyCaseStudy_fda_* > AnyCaseStudy_stitcher_input
ls AnyCaseStudy_npl_pmid >> AnyCaseStudy_stitcher_input
ls AnyCaseStudy_ct_*_pmid >> AnyCaseStudy_stitcher_input
ls AnyCaseStudy_pubmed_*_pmid >> AnyCaseStudy_stitcher_input

while read p; do
  if [[ -e $p ]]; 
  then echo  "\n$p exists "
  fi
  if [[ $(egrep ^[0-9]\{5,\}$ $p)  ]]; 
  then echo "AND $p content seems pmid-like"
  else echo "PROBLEM with $p"
  fi
done < AnyCaseStudy_stitcher_input

wc -l AnyCaseStudy_fda_medical_review_pmid > t1 
echo "AnyCaseStudy_fda_medical_review_pmid has $(cat t1 | awk '{print $1}') pmids"

wc -l AnyCaseStudy_fda_other_review_pmid > t2
echo "AnyCaseStudy_fda_medical_review_pmid has $(cat t2 | awk '{print $1}') pmids"

wc -l AnyCaseStudy_npl_pmid > t3
echo "AnyCaseStudy_fda_medical_review_pmid has $(cat t3 | awk '{print $1}') pmids"

wc -l AnyCaseStudy_ct_postapp_publication_pmid > t4
echo "AnyCaseStudy_fda_medical_review_pmid has $(cat t4 | awk '{print $1}') pmids"

wc -l AnyCaseStudy_ct_postapp_reference_pmid > t5
echo "AnyCaseStudy_fda_medical_review_pmid has $(cat t5 | awk '{print $1}') pmids"

wc -l AnyCaseStudy_ct_preapp_publication_pmid > t6
echo "AnyCaseStudy_fda_medical_review_pmid has $(cat t6 | awk '{print $1}') pmids"

wc -l AnyCaseStudy_ct_preapp_reference_pmid > t7
echo "AnyCaseStudy_fda_medical_review_pmid has $(cat t7 | awk '{print $1}') pmids"

wc -l AnyCaseStudy_pubmed_ct_postapp_pmid > t8
echo "AnyCaseStudy_fda_medical_review_pmid has $(cat t8 | awk '{print $1}') pmids"

wc -l AnyCaseStudy_pubmed_ct_preapp_pmid > t9
echo "AnyCaseStudy_fda_medical_review_pmid has $(cat t9 | awk '{print $1}') pmids"

wc -l AnyCaseStudy_pubmed_postapp_pmid > t10
echo "AnyCaseStudy_fda_medical_review_pmid has $(cat t10 | awk '{print $1}') pmids"

wc -l AnyCaseStudy_pubmed_preapp_pmid > t11
echo "AnyCaseStudy_fda_medical_review_pmid has $(cat t11 | awk '{print $1}') pmids"

sleep 2


echo "processing AnyCaseStudy_fda_medical_review_pmid"
# <!ELEMENT medical_review_pmid (#PCDATA)>
sed 's/^/\<AnyCaseStudy_fda_medical_review_pmid\>/g'  AnyCaseStudy_fda_medical_review_pmid |
 sed 's/$/\<\/AnyCaseStudy_fda_medical_review_pmid\>/g' > file1

echo "processing AnyCaseStudy_fda_other_review_pmid"
# <!ELEMENT fda_other_pmid (#PCDATA)>
sed 's/^/\<AnyCaseStudy_fda_other_pmid\>/g'  AnyCaseStudy_fda_other_review_pmid |
 sed 's/$/\<\/AnyCaseStudy_fda_other_pmid\>/g' > file2

echo "processing AnyCaseStudy_npl_pmid"
# <!ELEMENT npl_pmid (#PCDATA)>
sed 's/^/\<AnyCaseStudy_npl_pmid\>/g'  AnyCaseStudy_npl_pmid |
 sed 's/$/\<\/AnyCaseStudy_npl_pmid\>/g' > file3

echo "processing AnyCaseStudy_ct_preapp_reference_pmid"
# <!ELEMENT ct_preapp_references_pmid (#PCDATA)>
sed 's/^/\<ct_preapp_references_pmid\>/g'  AnyCaseStudy_ct_preapp_reference_pmid |
 sed 's/$/\<\/ct_preapp_references_pmid\>/g' > file4

echo "processing AnyCaseStudy_ct_preapp_publication_pmid"
#  <!ELEMENT ct_preapp_publication_pmid (#PCDATA)>
sed 's/^/\<ct_preapp_publication_pmid\>/g'  AnyCaseStudy_ct_preapp_publication_pmid |
 sed 's/$/\<\/ct_preapp_publication_pmid\>/g' > file5

echo "processing AnyCaseStudy_ct_postapp_reference_pmid"
#  <!ELEMENT ct_postapp_references_pmid (#PCDATA)>
sed 's/^/\<ct_postapp_reference_pmid\>/g'  AnyCaseStudy_ct_postapp_reference_pmid |
 sed 's/$/\<\/ct_postapp_reference_pmid\>/g' > file6

echo "processing AnyCaseStudy_ct_postapp_publication_pmid"
#   <!ELEMENT ct_postapp_publication_pmid (#PCDATA)>
sed 's/^/\<ct_postapp_publication_pmid\>/g'  AnyCaseStudy_ct_postapp_publication_pmid |
 sed 's/$/\<\/ct_postapp_publication_pmid\>/g' > file7

echo "processing AnyCaseStudy_pubmed_preapp_pmid"
#   <!ELEMENT pubmed_preapp_pmid (#PCDATA)>
sed 's/^/\<pubmed_preapp_pmid\>/g'  AnyCaseStudy_pubmed_preapp_pmid |
 sed 's/$/\<\/pubmed_preapp_pmid\>/g' > file8

echo "processing AnyCaseStudy_pubmed_postapp_pmid"
#   <!ELEMENT pubmed_postapp_pmid (#PCDATA)>
sed 's/^/\<pubmed_postapp_pmid\>/g'  AnyCaseStudy_pubmed_postapp_pmid |
 sed 's/$/\<\/pubmed_postapp_pmid\>/g' > file9

echo "processing AnyCaseStudy_pubmed_review_pmid"
#   <!ELEMENT pubmed_review_pmid (#PCDATA)>
sed 's/^/\<pubmed_review_pmid\>/g'  AnyCaseStudy_pubmed_review_pmid |
 sed 's/$/\<\/pubmed_review_pmid\>/g' > file10

echo "processing AnyCaseStudy_pubmed_ct_preapp_pmid"
#   <!ELEMENT pubmed_ct_preapp_pmid (#PCDATA)>
sed 's/^/\<AnyCaseStudy_pubmed_ct_preapp_pmid\>/g'  AnyCaseStudy_pubmed_ct_preapp_pmid |
 sed 's/$/\<\/AnyCaseStudy_pubmed_ct_preapp_pmid\>/g' > file11

echo "processing AnyCaseStudy_pubmed_ct_postapp_pmid"
#   <!ELEMENT pubmed_ct_postapp_pmid (#PCDATA)>
sed 's/^/\<pubmed_ct_postapp_pmid\>/g'  AnyCaseStudy_pubmed_ct_postapp_pmid |
 sed 's/$/\<\/pubmed_ct_postapp_pmid\>/g' > file12

for f in file*
do
    if [$(cat $f | wc -l) = 0 ]
	then
	    echo "*** $f is problematic"
	    else echo "$f has at least 1 line"
    fi
done

head -41 ~/ERNIE/Analysis/horizontal/seedset.dtd > AnyCaseStudy2.xml

echo "<drug>" >> AnyCaseStudy2.xml
echo "<fda>" >> AnyCaseStudy2.xml
cat file1 file2  >> AnyCaseStudy2.xml
echo "</fda>" >> AnyCaseStudy2.xml

echo "<patent>" >> AnyCaseStudy2.xml
cat file3  >> AnyCaseStudy2.xml
echo "</patent>" >> AnyCaseStudy2.xml

echo "<ct>" >> AnyCaseStudy2.xml
cat file4 file5 file6 file7  >> AnyCaseStudy2.xml
echo "</ct>" >> AnyCaseStudy2.xml

echo "<pubmed>" >> AnyCaseStudy2.xml
cat file8 file9 file10 file12 file12  >> AnyCaseStudy2.xml
echo "</pubmed>" >> AnyCaseStudy2.xml

echo "</drug>" >> AnyCaseStudy2.xml

xmllint --format AnyCaseStudy2.xml > AnyCaseStudy.xml
rm file1
rm file2
rm file3
rm file4
rm file5
rm file6
rm file7
rm file8
rm file9
rm file10
rm file11
rm file12
rm AnyCaseStudy2.xml

# Create seedset_pmid  file
#AnyCaseStudy_fda_medical_review_pmid
#AnyCaseStudy_fda_other_review_pmid
#AnyCaseStudy_npl_pmid
#AnyCaseStudy_ct_preapp_publication_pmid
#AnyCaseStudy_ct_preapp_reference_pmid
#AnyCaseStudy_pubmed_ct_preapp_pmid
#AnyCaseStudy_pubmed_preapp_pmid

cat AnyCaseStudy.xml | egrep _pmid\>[0-9]{3} > temp1
cat temp1 | egrep fda > temp2
cat temp1 | egrep npl_pmid > temp3
cat temp1 | egrep preapp > temp4
cat temp2 temp3 temp4 | cut -d '<' -f2 | cut -d '>' -f2 | sort | uniq > AnyCaseStudy_seedset_pmid_presql
cat AnyCaseStudy_seedset_pmid_presql | wc -l  > line_count1
echo "***"
echo "$(cat line_count1) seedset pmids for AnyCaseStudy"
echo "***"
rm temp1 temp2 temp3 temp4 line_count1

# Create postapp_pmid files
cp AnyCaseStudy_ct_postapp_publication_pmid temp1
cp AnyCaseStudy_ct_postapp_reference_pmid temp2
cp AnyCaseStudy_pubmed_ct_postapp_pmid temp3
cp AnyCaseStudy_pubmed_postapp_pmid temp4 
cat temp1 temp3 temp4 | sort | uniq > AnyCaseStudy_postapp_pmid_presql
cat AnyCaseStudy_postapp_pmid_presql | wc -l > line_count2
echo "***"
echo "$(cat line_count2) postapp pmids for AnyCaseStudy"
echo "***"
rm temp1 temp2 temp3 temp4 line_count2

# Create AnyCaseStudy_pubmed review file
cp AnyCaseStudy_pubmed_review_pmid temp1
cat temp1 | sort | uniq > AnyCaseStudy_review_pmid_presql
cat AnyCaseStudy_review_pmid_presql | wc -l > line_count3
echo "***"
echo "$(cat line_count3) review pmids for AnyCaseStudy"
echo "***"
rm temp1 line_count3
rm t[0-9]*





