\include_relative lexis_nexis_tables.sql

\include_relative Procedures/lexis_nexis_parse_abstracts.sql
\include_relative Procedures/lexis_nexis_parse_bibliographic_data.sql
\include_relative Procedures/lexis_nexis_parser_examiners.sql
\include_relative Procedures/lexis_nexis_parse_legal_data.sql
\include_relative Procedures/lexis_nexis_parse_nonpatent_citations.sql
\include_relative Procedures/lexis_nexis_parse_patent_citations.sql
\include_relative Procedures/lexis_nexis_parse_related_documents.sql
\include_relative Procedures/lexis_nexis_parse_application_references.sql
\include_relative Procedures/lexis_nexis_parse_priority_claims.sql
