#!/bin/bash
# George Chacko 12/01/2017

echo "This script takes a set of source files and modifies them to incorporate xml tags then
it assembles a complete xml file that is compliant with seedset.dtd

Input filenames with pmids in them should terminate in '_pmid' and should include

2 fda_*_pmid    files
1 npl_pmid      file
2 ct_*_pmid     files
2 pubmed_*_pmid files

Other input files relate to fda data and patent no

"
# sleep 1

ls ipilimumab_fda_*_pmid > ipilimumab_stitcher_input
ls ipilimumab_patent_npl_pmid >> ipilimumab_stitcher_input
ls ipilimumab_ct_*_pmid >> ipilimumab_stitcher_input
ls ipilimumab_pubmed_*_pmid >> ipilimumab_stitcher_input

while read p; do
  if [[ -e $p ]]; 
  then echo  "\n$p exists "
  fi
  if [[ $(egrep ^[0-9]\{5,\}$ $p)  ]]; 
  then echo "AND $p content seems pmid-like"
  else echo "PROBLEM with $p"
  fi
done < ipilimumab_stitcher_input

wc -l ipilimumab_fda_medical_review_pmid > t1 
echo "ipilimumab_fda_medical_review_pmid has $(cat t1 | awk '{print $1}') pmids"

wc -l ipilimumab_fda_other_review_pmid > t2
echo "ipilimumab_fda_other_review_pmid has $(cat t2 | awk '{print $1}') pmids"

wc -l ipilimumab_patent_npl_pmid > t3
echo "ipilimumab_patent_npl_pmid has $(cat t3 | awk '{print $1}') pmids"

wc -l ipilimumab_ct_publication_pmid > t4
echo "ipilimumab_ct_preapp_publication_pmid has $(cat t4 | awk '{print $1}') pmids"

wc -l ipilimumab_ct_reference_pmid > t5
echo "ipilimumab_ct_preapp_reference_pmid has $(cat t5 | awk '{print $1}') pmids"

wc -l ipilimumab_pubmed_preapp_pmid > t6
echo "ipilimumab_pubmed_preapp_pmid has $(cat t6 | awk '{print $1}') pmids"

sleep 2


echo "processing ipilimumab_fda_medical_review_pmid"
# <!ELEMENT fda_medical_review_pmid (#PCDATA)>
sed 's/^/\<ipilimumab_fda_medical_review_pmid\>/g'  ipilimumab_fda_medical_review_pmid | sed 's/$/\<\/ipilimumab_fda_medical_review_pmid\>/g' > file1

echo "processing ipilimumab_fda_other_review_pmid"
# <!ELEMENT fda_other_pmid (#PCDATA)>
sed 's/^/\<ipilimumab_fda_other_pmid\>/g'  ipilimumab_fda_other_review_pmid | sed 's/$/\<\/ipilimumab_fda_other_pmid\>/g' > file2

echo "processing ipilimumab_npl_pmid"
# <!ELEMENT npl_pmid (#PCDATA)>
sed 's/^/\<ipilimumab_npl_pmid\>/g'  ipilimumab_patent_npl_pmid | sed 's/$/\<\/ipilimumab_npl_pmid\>/g' > file3

echo "processing ipilimumab_ct_reference_pmid"
# <!ELEMENT ct_reference_pmid (#PCDATA)>
sed 's/^/\<ct_preapp_reference_pmid\>/g'  ipilimumab_ct_reference_pmid | sed 's/$/\<\/ct_preapp_reference_pmid\>/g' > file4

echo "processing ipilimumab_ct_publication_pmid"
#  <!ELEMENT ct_publication_pmid (#PCDATA)>
sed 's/^/\<ct_publication_pmid\>/g'  ipilimumab_ct_publication_pmid | sed 's/$/\<\/ct_publication_pmid\>/g' > file5

echo "processing ipilimumab_pubmed_preapp_pmid"
#   <!ELEMENT pubmed_preapp_pmid (#PCDATA)>
sed 's/^/\<pubmed_preapp_pmid\>/g'  ipilimumab_pubmed_preapp_pmid | sed 's/$/\<\/pubmed_preapp_pmid\>/g' > file6

for f in file*
do
    if [$(cat $f | wc -l) = 0 ]
	then
	    echo "*** $f is problematic"
	    else echo "$f has at least 1 line"
    fi
done

head -37 ~/ERNIE/Analysis/horizontal/seedset.dtd > ipilimumab2.xml

echo "<drug>" >> ipilimumab2.xml
echo "<fda>" >> ipilimumab2.xml
 cat ipilimumab_fda_brand_name >> ipilimumab2.xml
 cat ipilimumab_fda_active_ingredient >> ipilimumab2.xml
 cat ipilimumab_fda_bla >> ipilimumab2.xml
 cat ipilimumab_fda_source >> ipilimumab2.xml
 cat file1 file2  >> ipilimumab2.xml
echo "</fda>" >> ipilimumab2.xml

echo "<patent>" >> ipilimumab2.xml
cat ipilimumab_patent_pl_USpatentno >> ipilimumab2.xml
cat file3  >> ipilimumab2.xml
echo "</patent>" >> ipilimumab2.xml

echo "<ct>" >> ipilimumab2.xml
cat file4 file5  >> ipilimumab2.xml
echo "</ct>" >> ipilimumab2.xml

echo "<pubmed>" >> ipilimumab2.xml
cat file6  >> ipilimumab2.xml
echo "</pubmed>" >> ipilimumab2.xml

echo "</drug>" >> ipilimumab2.xml

xmllint --format ipilimumab2.xml > ipilimumab.xml

# Create seedset_pmid  file
#ipilimumab_fda_medical_review_pmid
#ipilimumab_fda_other_review_pmid
#ipilimumab_patent_npl_pmid
#ipilimumab_ct_preapp_publication_pmid
#ipilimumab_ct_preapp_reference_pmid
#ipilimumab_pubmed_ct_preapp_pmid
#ipilimumab_pubmed_preapp_pmid

cat ipilimumab.xml | egrep _pmid\>[0-9]{3} > temp1
cat temp1 | egrep fda > temp2
cat temp1 | egrep npl_pmid > temp3
cat temp1 | egrep preapp > temp4
cat temp2 temp3 temp4 | cut -d '<' -f2 | cut -d '>' -f2 | sort | uniq > ipilimumab_seedset_pmid_presql
cat ipilimumab_seedset_pmid_presql | wc -l  > line_count1
echo "***"
echo "$(cat line_count1) seedset pmids for ipilimumab"
echo "***"
rm temp1 temp2 temp3 temp4 line_count1

rm t[0-9]*





