#!/bin/bash
echo "This script takes a set of source files and modifies them to incorporate xml tags then
it assembles a complete xml file that is compliant with seedset.dtd"
:'
ipilimumab_fda_medical_review_pmid
ipilimumab_fda_other_review_pmid
ipilimumab_npl_pmid
ipilimumab_ct_postapp_publication_pmid
ipilimumab_ct_postapp_reference_pmid
ipilimumab_ct_preapp_publication_pmid
ipilimumab_ct_preapp_reference_pmid
ipilimumab_pubmed_ct_postapp_pmid
ipilimumab_pubmed_ct_preapp_pmid
ipilimumab_pubmed_postapp_pmid
ipilimumab_pubmed_preapp_pmid
ipilimumab_pubmed_review_pmid
'
echo "processing ipilimumab_fda_medical_review_pmid"
# <!ELEMENT medical_review_pmid (#PCDATA)>
sed 's/^/\<ipilimumab_fda_medical_review_pmid\>/g'  ipilimumab_fda_medical_review_pmid |
 sed 's/$/\<\/ipilimumab_fda_medical_review_pmid\>/g' > file1

echo "processing ipilimumab_fda_other_review_pmid"
# <!ELEMENT fda_other_pmid (#PCDATA)>
sed 's/^/\<ipilimumab_fda_other_pmid\>/g'  ipilimumab_fda_other_review_pmid |
 sed 's/$/\<\/ipilimumab_fda_other_pmid\>/g' > file2

echo "processing ipilimumab_npl_pmid"
# <!ELEMENT npl_pmid (#PCDATA)>
sed 's/^/\<ipilimumab_npl_pmid\>/g'  ipilimumab_npl_pmid |
 sed 's/$/\<\/ipilimumab_npl_pmid\>/g' > file3

echo "processing ipilimumab_ct_preapp_reference_pmid"
# <!ELEMENT ct_preapp_references_pmid (#PCDATA)>
sed 's/^/\<ct_preapp_references_pmid\>/g'  ipilimumab_ct_preapp_reference_pmid |
 sed 's/$/\<\/ct_preapp_references_pmid\>/g' > file4

echo "processing ipilimumab_ct_preapp_publication_pmid"
#  <!ELEMENT ct_preapp_publication_pmid (#PCDATA)>
sed 's/^/\<ct_preapp_publication_pmid\>/g'  ipilimumab_ct_preapp_publication_pmid |
 sed 's/$/\<\/ct_preapp_publication_pmid\>/g' > file5

echo "processing ipilimumab_ct_postapp_reference_pmid"
#  <!ELEMENT ct_postapp_references_pmid (#PCDATA)>
sed 's/^/\<ct_postapp_reference_pmid\>/g'  ipilimumab_ct_postapp_reference_pmid |
 sed 's/$/\<\/ct_postapp_reference_pmid\>/g' > file6

echo "processing ipilimumab_ct_postapp_publication_pmid"
#   <!ELEMENT ct_postapp_publication_pmid (#PCDATA)>
sed 's/^/\<ct_postapp_publication_pmid\>/g'  ipilimumab_ct_postapp_publication_pmid |
 sed 's/$/\<\/ct_postapp_publication_pmid\>/g' > file7

echo "processing ipilimumab_pubmed_preapp_pmid"
#   <!ELEMENT pubmed_preapp_pmid (#PCDATA)>
sed 's/^/\<pubmed_preapp_pmid\>/g'  ipilimumab_pubmed_preapp_pmid |
 sed 's/$/\<\/pubmed_preapp_pmid\>/g' > file8

echo "processing ipilimumab_pubmed_postapp_pmid"
#   <!ELEMENT pubmed_postapp_pmid (#PCDATA)>
sed 's/^/\<pubmed_postapp_pmid\>/g'  ipilimumab_pubmed_postapp_pmid |
 sed 's/$/\<\/pubmed_postapp_pmid\>/g' > file9

echo "processing ipilimumab_pubmed_review_pmid"
#   <!ELEMENT pubmed_review_pmid (#PCDATA)>
sed 's/^/\<pubmed_review_pmid\>/g'  ipilimumab_pubmed_review_pmid |
 sed 's/$/\<\/pubmed_review_pmid\>/g' > file10

echo "processing ipilimumab_pubmed_ct_preapp_pmid"
#   <!ELEMENT pubmed_ct_preapp_pmid (#PCDATA)>
sed 's/^/\<ipilimumab_pubmed_ct_preapp_pmid\>/g'  ipilimumab_pubmed_ct_preapp_pmid |
 sed 's/$/\<\/ipilimumab_pubmed_ct_preapp_pmid\>/g' > file11

echo "processing ipilimumab_pubmed_ct_postapp_pmid"
#   <!ELEMENT pubmed_ct_postapp_pmid (#PCDATA)>
sed 's/^/\<pubmed_ct_postapp_pmid\>/g'  ipilimumab_pubmed_ct_postapp_pmid |
 sed 's/$/\<\/pubmed_ct_postapp_pmid\>/g' > file12

head -41 ~/ERNIE/Analysis/horizontal/seedset.dtd > ipilimumab2.xml

echo "<drug>" >> ipilimumab2.xml
echo "<fda>" >> ipilimumab2.xml
cat file1 file2  >> ipilimumab2.xml
echo "</fda>" >> ipilimumab2.xml

echo "<patent>" >> ipilimumab2.xml
cat file3  >> ipilimumab2.xml
echo "</patent>" >> ipilimumab2.xml

echo "<ct>" >> ipilimumab2.xml
cat file4 file5 file6 file7  >> ipilimumab2.xml
echo "</ct>" >> ipilimumab2.xml

echo "<pubmed>" >> ipilimumab2.xml
cat file8 file9 file10 file12 file12  >> ipilimumab2.xml
echo "</pubmed>" >> ipilimumab2.xml

echo "</drug>" >> ipilimumab2.xml

xmllint --format ipilimumab2.xml > ipilimumab.xml
rm file1
rm file2
rm file3
rm file4
rm file5
rm file6
rm file7
rm file8
rm file9
rm file11
rm file11
rm file12
rm ipilimumab2.xml













