xn <- x[,.(cluster,
countsn=counts/counts,
ain=ai/counts,
ct_mn=ct_m/counts,
cg_cadn=cg_cad/counts,
cn_cn=cn_c/counts,
csan=csa/counts,
cv_prn=cv_pr/counts,
h_an=h_a/counts,
hcin=hci/counts,
isn=is/counts,
spn=sp/counts,
swn=sw/counts,
miscn=misc/counts,
alln=all/counts
)]